from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from app.domain.infrastructure_ontology import (
    ACTIVE_STATUS,
    INFRASTRUCTURE_EXIT_EVENT_BY_STAGE,
    INFRASTRUCTURE_SOURCE_SYSTEM,
    INFRASTRUCTURE_STAGE_FLOW,
    INFRASTRUCTURE_STAGE_THRESHOLDS_HOURS,
    TERMINAL_STAGE,
    TERMINAL_STATUS,
)


@dataclass(frozen=True)
class InfrastructureScenarioProfile:
    scenario_key: str
    title: str
    asset_id: str
    required_spare_id: str | None
    assigned_engineer_id: str | None
    incident_type: str
    priority_level: str
    failure_mode: str
    business_impact: str
    needed_by_offset_hours: int
    estimated_downtime_hours: int
    stage_durations_hours: dict[str, int]
    stop_stage: str | None = None
    validation_failed_once: bool = False
    telemetry_alert_type: str | None = None
    redundancy_state: str = "N+1"
    affected_rack_count: int = 0
    affected_gpu_count: int = 0
    estimated_capacity_risk_kw: int = 0
    estimated_gpu_capacity_risk_pct: float = 0
    thermal_breach_minutes: int = 0
    power_redundancy_lost: bool = False
    cooling_redundancy_lost: bool = False
    mitigation_status: str = "NONE"
    vendor_eta_offset_hours: int | None = None
    vendor_status: str = "NOT_REQUIRED"
    telemetry_readings: tuple[dict[str, Any], ...] = ()


INFRASTRUCTURE_SCENARIO_PROFILES = [
    InfrastructureScenarioProfile(
        scenario_key="completed_crac_fan_replacement",
        title="Routine CRAH fan array replacement",
        asset_id="ASSET-CRAH-01",
        required_spare_id="SPARE-CRAH-FAN",
        assigned_engineer_id="ENG-MECH-01",
        incident_type="PREVENTIVE",
        priority_level="MEDIUM",
        failure_mode="FAN_BEARING_WEAR",
        business_impact="PLANNED_COOLING_MAINTENANCE",
        needed_by_offset_hours=120,
        estimated_downtime_hours=4,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 3,
            "ENGINEER_ASSIGNED": 2,
            "SPARE_VENDOR_WAITING": 2,
            "REPAIR_IN_PROGRESS": 5,
            "VALIDATION": 2,
        },
        mitigation_status="VERIFIED_NORMAL",
    ),
    InfrastructureScenarioProfile(
        scenario_key="ups_module_triage_delay",
        title="UPS module alarm triage delay",
        asset_id="ASSET-UPS-01",
        required_spare_id="SPARE-UPS-MODULE",
        assigned_engineer_id=None,
        incident_type="CORRECTIVE",
        priority_level="HIGH",
        failure_mode="UPS_BYPASS_ALARM",
        business_impact="POWER_REDUNDANCY_RISK",
        needed_by_offset_hours=36,
        estimated_downtime_hours=10,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 38,
        },
        stop_stage="FACILITIES_TRIAGE",
        telemetry_alert_type="UPS_BYPASS_ALARM",
        redundancy_state="N",
        affected_rack_count=18,
        affected_gpu_count=144,
        estimated_capacity_risk_kw=450,
        estimated_gpu_capacity_risk_pct=18.0,
        power_redundancy_lost=True,
        mitigation_status="NONE",
        telemetry_readings=(
            {"metric": "ups_load_pct", "value": 83.0, "unit": "percent", "status": "WARNING"},
            {"metric": "battery_runtime_minutes", "value": 11.0, "unit": "minutes", "status": "WARNING"},
        ),
    ),
    InfrastructureScenarioProfile(
        scenario_key="pdu_breaker_assignment_delay",
        title="PDU breaker trip engineer assignment",
        asset_id="ASSET-PDU-01",
        required_spare_id="SPARE-BREAKER-MODULE",
        assigned_engineer_id=None,
        incident_type="BREAKDOWN",
        priority_level="HIGH",
        failure_mode="BREAKER_TRIP",
        business_impact="GPU_RACK_POWER_RISK",
        needed_by_offset_hours=24,
        estimated_downtime_hours=14,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 5,
            "ENGINEER_ASSIGNED": 29,
        },
        stop_stage="ENGINEER_ASSIGNED",
        telemetry_alert_type="BRANCH_CIRCUIT_TRIP",
        redundancy_state="N",
        affected_rack_count=6,
        affected_gpu_count=48,
        estimated_capacity_risk_kw=160,
        estimated_gpu_capacity_risk_pct=6.0,
        power_redundancy_lost=True,
        mitigation_status="RUNNING_DEGRADED",
        telemetry_readings=(
            {"metric": "branch_current_amps", "value": 0.0, "unit": "amps", "status": "CRITICAL"},
            {"metric": "rack_power_available_pct", "value": 72.0, "unit": "percent", "status": "WARNING"},
        ),
    ),
    InfrastructureScenarioProfile(
        scenario_key="chiller_spare_waiting_delay",
        title="Chiller compressor replacement waiting on vendor",
        asset_id="ASSET-CHILLER-01",
        required_spare_id="SPARE-CHILLER-COMPRESSOR",
        assigned_engineer_id="ENG-MECH-02",
        incident_type="BREAKDOWN",
        priority_level="CRITICAL",
        failure_mode="COMPRESSOR_FAILURE",
        business_impact="GPU_COOLING_CAPACITY_AT_RISK",
        needed_by_offset_hours=12,
        estimated_downtime_hours=22,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 3,
            "ENGINEER_ASSIGNED": 4,
            "SPARE_VENDOR_WAITING": 86,
        },
        stop_stage="SPARE_VENDOR_WAITING",
        telemetry_alert_type="CHILLED_WATER_TEMP_HIGH",
        redundancy_state="N",
        affected_rack_count=32,
        affected_gpu_count=256,
        estimated_capacity_risk_kw=620,
        estimated_gpu_capacity_risk_pct=32.0,
        thermal_breach_minutes=75,
        cooling_redundancy_lost=True,
        mitigation_status="LOAD_SHIFTED",
        vendor_eta_offset_hours=34,
        vendor_status="WAITING_VENDOR_DISPATCH",
        telemetry_readings=(
            {"metric": "supply_water_temp_c", "value": 18.7, "unit": "celsius", "status": "CRITICAL"},
            {"metric": "gpu_hall_return_temp_c", "value": 31.4, "unit": "celsius", "status": "CRITICAL"},
        ),
    ),
    InfrastructureScenarioProfile(
        scenario_key="cdu_repair_in_progress_delay",
        title="CDU coolant flow repair in progress",
        asset_id="ASSET-CDU-01",
        required_spare_id="SPARE-COOLANT-PUMP-SEAL",
        assigned_engineer_id="ENG-MECH-03",
        incident_type="CORRECTIVE",
        priority_level="HIGH",
        failure_mode="COOLANT_FLOW_LOW",
        business_impact="LIQUID_COOLING_LOOP_RISK",
        needed_by_offset_hours=48,
        estimated_downtime_hours=16,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 4,
            "ENGINEER_ASSIGNED": 3,
            "SPARE_VENDOR_WAITING": 4,
            "REPAIR_IN_PROGRESS": 72,
        },
        stop_stage="REPAIR_IN_PROGRESS",
        redundancy_state="N",
        affected_rack_count=10,
        affected_gpu_count=80,
        estimated_capacity_risk_kw=210,
        estimated_gpu_capacity_risk_pct=10.0,
        cooling_redundancy_lost=True,
        mitigation_status="RUNNING_DEGRADED",
        telemetry_readings=(
            {"metric": "coolant_flow_lpm", "value": 52.0, "unit": "lpm", "status": "WARNING"},
            {"metric": "loop_delta_t_c", "value": 8.8, "unit": "celsius", "status": "WARNING"},
        ),
    ),
    InfrastructureScenarioProfile(
        scenario_key="thermal_validation_delay",
        title="Data hall thermal validation delay",
        asset_id="ASSET-CRAH-02",
        required_spare_id="SPARE-TEMP-SENSOR",
        assigned_engineer_id="ENG-ELEC-01",
        incident_type="VALIDATION_FINDING",
        priority_level="HIGH",
        failure_mode="THERMAL_VALIDATION_FAILED",
        business_impact="GPU_ZONE_RETURN_TO_SERVICE_HOLD",
        needed_by_offset_hours=30,
        estimated_downtime_hours=8,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 3,
            "ENGINEER_ASSIGNED": 2,
            "SPARE_VENDOR_WAITING": 3,
            "REPAIR_IN_PROGRESS": 10,
            "VALIDATION": 44,
        },
        stop_stage="VALIDATION",
        validation_failed_once=True,
        redundancy_state="N+1",
        affected_rack_count=14,
        affected_gpu_count=112,
        estimated_capacity_risk_kw=300,
        estimated_gpu_capacity_risk_pct=14.0,
        thermal_breach_minutes=96,
        mitigation_status="LOAD_SHIFTED",
        telemetry_readings=(
            {"metric": "rack_inlet_temp_c", "value": 30.8, "unit": "celsius", "status": "CRITICAL"},
            {"metric": "thermal_validation_pass_rate_pct", "value": 68.0, "unit": "percent", "status": "WARNING"},
        ),
    ),
    InfrastructureScenarioProfile(
        scenario_key="generator_vendor_waiting_delay",
        title="Backup generator fuel system vendor wait",
        asset_id="ASSET-GEN-01",
        required_spare_id="SPARE-FUEL-PUMP",
        assigned_engineer_id="ENG-MECH-04",
        incident_type="BREAKDOWN",
        priority_level="CRITICAL",
        failure_mode="FUEL_PUMP_FAILURE",
        business_impact="BACKUP_POWER_CAPACITY_RISK",
        needed_by_offset_hours=8,
        estimated_downtime_hours=30,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 2,
            "ENGINEER_ASSIGNED": 4,
            "SPARE_VENDOR_WAITING": 58,
        },
        stop_stage="SPARE_VENDOR_WAITING",
        telemetry_alert_type="GENERATOR_START_FAILURE",
        redundancy_state="N-1",
        affected_rack_count=40,
        affected_gpu_count=320,
        estimated_capacity_risk_kw=900,
        estimated_gpu_capacity_risk_pct=40.0,
        power_redundancy_lost=True,
        mitigation_status="RUNNING_DEGRADED",
        vendor_eta_offset_hours=20,
        vendor_status="ETA_MISSED",
        telemetry_readings=(
            {"metric": "generator_start_success", "value": 0.0, "unit": "boolean", "status": "CRITICAL"},
            {"metric": "fuel_pressure_psi", "value": 18.0, "unit": "psi", "status": "CRITICAL"},
        ),
    ),
    InfrastructureScenarioProfile(
        scenario_key="repeated_crah_fan_failure",
        title="Repeated CRAH fan fault in GPU hall",
        asset_id="ASSET-CRAH-01",
        required_spare_id="SPARE-CRAH-FAN",
        assigned_engineer_id="ENG-MECH-01",
        incident_type="CORRECTIVE",
        priority_level="HIGH",
        failure_mode="FAN_SPEED_DRIFT",
        business_impact="HOT_AISLE_TEMPERATURE_RISK",
        needed_by_offset_hours=40,
        estimated_downtime_hours=12,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 4,
            "ENGINEER_ASSIGNED": 4,
            "SPARE_VENDOR_WAITING": 3,
            "REPAIR_IN_PROGRESS": 18,
            "VALIDATION": 4,
        },
        redundancy_state="N+1",
        affected_rack_count=4,
        affected_gpu_count=32,
        estimated_capacity_risk_kw=90,
        estimated_gpu_capacity_risk_pct=4.0,
        thermal_breach_minutes=22,
        mitigation_status="VERIFIED_NORMAL",
    ),
    InfrastructureScenarioProfile(
        scenario_key="gpu_zone_temperature_assignment_delay",
        title="GPU zone inlet temperature engineer assignment",
        asset_id="ASSET-RACK-01",
        required_spare_id="SPARE-RACK-TEMP-SENSOR",
        assigned_engineer_id="ENG-ELEC-02",
        incident_type="CORRECTIVE",
        priority_level="MEDIUM",
        failure_mode="INLET_TEMPERATURE_HIGH",
        business_impact="AI_WORKLOAD_THROTTLING_RISK",
        needed_by_offset_hours=56,
        estimated_downtime_hours=9,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 5,
            "ENGINEER_ASSIGNED": 12,
        },
        stop_stage="ENGINEER_ASSIGNED",
        telemetry_alert_type="RACK_INLET_TEMP_HIGH",
        redundancy_state="N+1",
        affected_rack_count=8,
        affected_gpu_count=64,
        estimated_capacity_risk_kw=180,
        estimated_gpu_capacity_risk_pct=8.0,
        thermal_breach_minutes=48,
        mitigation_status="LOAD_SHIFTED",
        telemetry_readings=(
            {"metric": "rack_inlet_temp_c", "value": 29.9, "unit": "celsius", "status": "WARNING"},
            {"metric": "gpu_throttle_events", "value": 17.0, "unit": "count", "status": "WARNING"},
        ),
    ),
    InfrastructureScenarioProfile(
        scenario_key="epms_telemetry_follow_up",
        title="EPMS telemetry anomaly follow-up",
        asset_id="ASSET-SWGR-01",
        required_spare_id="SPARE-POWER-METER",
        assigned_engineer_id="ENG-ELEC-01",
        incident_type="TELEMETRY_TRIGGERED",
        priority_level="MEDIUM",
        failure_mode="POWER_METER_DRIFT",
        business_impact="CAPACITY_PLANNING_TRUST_RISK",
        needed_by_offset_hours=72,
        estimated_downtime_hours=6,
        stage_durations_hours={
            "INCIDENT_REPORTED": 1,
            "FACILITIES_TRIAGE": 5,
            "ENGINEER_ASSIGNED": 4,
            "SPARE_VENDOR_WAITING": 5,
            "REPAIR_IN_PROGRESS": 8,
            "VALIDATION": 3,
        },
        telemetry_alert_type="POWER_READING_MISMATCH",
        redundancy_state="N+1",
        affected_rack_count=0,
        affected_gpu_count=0,
        estimated_capacity_risk_kw=0,
        estimated_gpu_capacity_risk_pct=0,
        mitigation_status="VERIFIED_NORMAL",
        telemetry_readings=(
            {"metric": "meter_variance_pct", "value": 7.4, "unit": "percent", "status": "WARNING"},
        ),
    ),
]
