"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-05-23 00:21:38.860285+00:00
"""

from collections.abc import Sequence
from typing import Optional, Union

from alembic import op
import sqlalchemy as sa



revision: str = '0001_initial_schema'
down_revision: Optional[str] = None
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottleneck_summary',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('dimension_type', sa.String(length=40), nullable=False),
    sa.Column('dimension_id', sa.String(length=80), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('delayed_count', sa.Integer(), nullable=False),
    sa.Column('avg_duration_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('p90_duration_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_delay_hours', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('pk_bottleneck_summary'))
    )
    op.create_index('ix_bottleneck_summary_date_dimension', 'bottleneck_summary', ['summary_date', 'dimension_type', 'dimension_id'], unique=False)
    op.create_index('ix_bottleneck_summary_stage_delay', 'bottleneck_summary', ['stage', 'total_delay_hours'], unique=False)
    op.create_table('data_quality_check_results',
    sa.Column('check_result_id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=64), nullable=False),
    sa.Column('check_name', sa.String(length=160), nullable=False),
    sa.Column('target_table', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('failed_row_count', sa.Integer(), nullable=False),
    sa.Column('sample_failed_keys', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('check_result_id', name=op.f('pk_data_quality_check_results'))
    )
    op.create_index(op.f('ix_data_quality_check_results_pipeline_run_id'), 'data_quality_check_results', ['pipeline_run_id'], unique=False)
    op.create_index('ix_dq_results_run_status', 'data_quality_check_results', ['pipeline_run_id', 'status'], unique=False)
    op.create_index('ix_dq_results_severity', 'data_quality_check_results', ['severity'], unique=False)
    op.create_index('ix_dq_results_target_table', 'data_quality_check_results', ['target_table'], unique=False)
    op.create_table('departments',
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('department_name', sa.String(length=160), nullable=False),
    sa.Column('department_type', sa.String(length=80), nullable=False),
    sa.Column('cost_center', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('department_id', name=op.f('pk_departments')),
    sa.UniqueConstraint('department_name', name=op.f('uq_departments_department_name'))
    )
    op.create_table('items',
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_category', sa.String(length=80), nullable=False),
    sa.Column('is_critical_item', sa.Boolean(), nullable=False),
    sa.Column('standard_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_items'))
    )
    op.create_index('ix_items_category_critical', 'items', ['item_category', 'is_critical_item'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('pipeline_run_id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_name', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('rows_extracted', sa.Integer(), nullable=False),
    sa.Column('rows_loaded', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pipeline_run_id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index('ix_pipeline_runs_name_started', 'pipeline_runs', ['pipeline_name', 'started_at'], unique=False)
    op.create_index('ix_pipeline_runs_status', 'pipeline_runs', ['status'], unique=False)
    op.create_table('raw_purchase_orders',
    sa.Column('raw_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_record_id', sa.String(length=120), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('raw_id', name=op.f('pk_raw_purchase_orders')),
    sa.UniqueConstraint('source_system', 'source_record_id', name='uq_raw_po_source_record')
    )
    op.create_index('ix_raw_po_pipeline_source', 'raw_purchase_orders', ['pipeline_run_id', 'source_system'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_pipeline_run_id'), 'raw_purchase_orders', ['pipeline_run_id'], unique=False)
    op.create_table('raw_purchase_requests',
    sa.Column('raw_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_record_id', sa.String(length=120), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('raw_id', name=op.f('pk_raw_purchase_requests')),
    sa.UniqueConstraint('source_system', 'source_record_id', name='uq_raw_pr_source_record')
    )
    op.create_index('ix_raw_pr_pipeline_source', 'raw_purchase_requests', ['pipeline_run_id', 'source_system'], unique=False)
    op.create_index(op.f('ix_raw_purchase_requests_pipeline_run_id'), 'raw_purchase_requests', ['pipeline_run_id'], unique=False)
    op.create_table('raw_receipts',
    sa.Column('raw_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_record_id', sa.String(length=120), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('raw_id', name=op.f('pk_raw_receipts')),
    sa.UniqueConstraint('source_system', 'source_record_id', name='uq_raw_receipt_source_record')
    )
    op.create_index('ix_raw_receipt_pipeline_source', 'raw_receipts', ['pipeline_run_id', 'source_system'], unique=False)
    op.create_index(op.f('ix_raw_receipts_pipeline_run_id'), 'raw_receipts', ['pipeline_run_id'], unique=False)
    op.create_table('raw_stage_events',
    sa.Column('raw_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_record_id', sa.String(length=120), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('raw_id', name=op.f('pk_raw_stage_events')),
    sa.UniqueConstraint('source_system', 'source_record_id', name='uq_raw_stage_event_source_record')
    )
    op.create_index('ix_raw_stage_event_pipeline_source', 'raw_stage_events', ['pipeline_run_id', 'source_system'], unique=False)
    op.create_index(op.f('ix_raw_stage_events_pipeline_run_id'), 'raw_stage_events', ['pipeline_run_id'], unique=False)
    op.create_table('raw_vendor_updates',
    sa.Column('raw_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_record_id', sa.String(length=120), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('raw_id', name=op.f('pk_raw_vendor_updates')),
    sa.UniqueConstraint('source_system', 'source_record_id', name='uq_raw_vendor_update_source_record')
    )
    op.create_index('ix_raw_vendor_update_pipeline_source', 'raw_vendor_updates', ['pipeline_run_id', 'source_system'], unique=False)
    op.create_index(op.f('ix_raw_vendor_updates_pipeline_run_id'), 'raw_vendor_updates', ['pipeline_run_id'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.String(length=64), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_type', sa.String(length=80), nullable=False),
    sa.Column('reliability_tier', sa.String(length=40), nullable=False),
    sa.Column('default_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('vendor_name', name=op.f('uq_vendors_vendor_name'))
    )
    op.create_index('ix_vendors_reliability_tier', 'vendors', ['reliability_tier'], unique=False)
    op.create_table('requesters',
    sa.Column('requester_id', sa.String(length=64), nullable=False),
    sa.Column('requester_name', sa.String(length=160), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], name=op.f('fk_requesters_department_id_departments')),
    sa.PrimaryKeyConstraint('requester_id', name=op.f('pk_requesters'))
    )
    op.create_index('ix_requesters_department_id', 'requesters', ['department_id'], unique=False)
    op.create_table('vendor_delay_summary',
    sa.Column('vendor_id', sa.String(length=64), nullable=False),
    sa.Column('total_po_count', sa.Integer(), nullable=False),
    sa.Column('delayed_po_count', sa.Integer(), nullable=False),
    sa.Column('delay_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('avg_confirmation_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_delivery_delay_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reliability_tier', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], name=op.f('fk_vendor_delay_summary_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('vendor_id', name=op.f('pk_vendor_delay_summary'))
    )
    op.create_index('ix_vendor_delay_summary_delay_rate', 'vendor_delay_summary', ['delay_rate'], unique=False)
    op.create_table('purchase_requests',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('request_number', sa.String(length=80), nullable=False),
    sa.Column('request_title', sa.String(length=240), nullable=False),
    sa.Column('request_type', sa.String(length=80), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('requester_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('criticality_level', sa.String(length=20), nullable=False),
    sa.Column('business_impact', sa.String(length=80), nullable=False),
    sa.Column('needed_by_date', sa.Date(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_stage', sa.String(length=60), nullable=False),
    sa.Column('current_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], name=op.f('fk_purchase_requests_department_id_departments')),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], name=op.f('fk_purchase_requests_item_id_items')),
    sa.ForeignKeyConstraint(['requester_id'], ['requesters.requester_id'], name=op.f('fk_purchase_requests_requester_id_requesters')),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_purchase_requests')),
    sa.UniqueConstraint('request_number', name='uq_purchase_requests_request_number')
    )
    op.create_index('ix_purchase_requests_criticality_needed_by', 'purchase_requests', ['criticality_level', 'needed_by_date'], unique=False)
    op.create_index('ix_purchase_requests_current_stage', 'purchase_requests', ['current_stage'], unique=False)
    op.create_index('ix_purchase_requests_department_status', 'purchase_requests', ['department_id', 'current_status'], unique=False)
    op.create_table('critical_request_queue',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('criticality_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('delay_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('business_impact_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('needed_by_urgency_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('vendor_risk_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_priority_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('recommended_action', sa.String(length=240), nullable=False),
    sa.Column('reason_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.request_id'], name=op.f('fk_critical_request_queue_request_id_purchase_requests')),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_critical_request_queue'))
    )
    op.create_index('ix_critical_request_queue_rank', 'critical_request_queue', ['priority_rank'], unique=False)
    op.create_index('ix_critical_request_queue_score', 'critical_request_queue', ['total_priority_score'], unique=False)
    op.create_table('procurement_stage_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('event_status', sa.String(length=60), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=60), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('reason_code', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.request_id'], name=op.f('fk_procurement_stage_events_request_id_purchase_requests')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_procurement_stage_events'))
    )
    op.create_index('ix_procurement_stage_events_request_time', 'procurement_stage_events', ['request_id', 'occurred_at'], unique=False)
    op.create_index('ix_procurement_stage_events_stage_time', 'procurement_stage_events', ['stage', 'occurred_at'], unique=False)
    op.create_index('ix_procurement_stage_events_type_status', 'procurement_stage_events', ['event_type', 'event_status'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.String(length=64), nullable=False),
    sa.Column('po_number', sa.String(length=80), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.String(length=64), nullable=False),
    sa.Column('po_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vendor_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('po_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.request_id'], name=op.f('fk_purchase_orders_request_id_purchase_requests')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], name=op.f('fk_purchase_orders_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('po_id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('po_number', name='uq_purchase_orders_po_number')
    )
    op.create_index('ix_purchase_orders_request_id', 'purchase_orders', ['request_id'], unique=False)
    op.create_index('ix_purchase_orders_vendor_status', 'purchase_orders', ['vendor_id', 'po_status'], unique=False)
    op.create_table('request_current_status',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('current_stage', sa.String(length=60), nullable=False),
    sa.Column('current_status', sa.String(length=60), nullable=False),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('days_in_current_stage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.Column('delay_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('needed_by_date', sa.Date(), nullable=False),
    sa.Column('criticality_level', sa.String(length=20), nullable=False),
    sa.Column('business_impact', sa.String(length=80), nullable=False),
    sa.Column('next_owner_type', sa.String(length=60), nullable=True),
    sa.Column('next_owner_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.request_id'], name=op.f('fk_request_current_status_request_id_purchase_requests')),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_request_current_status'))
    )
    op.create_index('ix_request_current_status_criticality_delay', 'request_current_status', ['criticality_level', 'delay_days'], unique=False)
    op.create_index('ix_request_current_status_stage_delayed', 'request_current_status', ['current_stage', 'is_delayed'], unique=False)
    op.create_table('request_stage_lead_times',
    sa.Column('lead_time_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('threshold_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_bottleneck', sa.Boolean(), nullable=False),
    sa.Column('delay_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.request_id'], name=op.f('fk_request_stage_lead_times_request_id_purchase_requests')),
    sa.PrimaryKeyConstraint('lead_time_id', name=op.f('pk_request_stage_lead_times'))
    )
    op.create_index('ix_request_stage_lead_times_request_stage', 'request_stage_lead_times', ['request_id', 'stage'], unique=False)
    op.create_index('ix_request_stage_lead_times_stage_bottleneck', 'request_stage_lead_times', ['stage', 'is_bottleneck'], unique=False)
    op.create_table('receipts',
    sa.Column('receipt_id', sa.String(length=64), nullable=False),
    sa.Column('po_id', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('inspection_status', sa.String(length=60), nullable=False),
    sa.Column('inspection_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], name=op.f('fk_receipts_po_id_purchase_orders')),
    sa.PrimaryKeyConstraint('receipt_id', name=op.f('pk_receipts'))
    )
    op.create_index('ix_receipts_po_inspection', 'receipts', ['po_id', 'inspection_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipts_po_inspection', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index('ix_request_stage_lead_times_stage_bottleneck', table_name='request_stage_lead_times')
    op.drop_index('ix_request_stage_lead_times_request_stage', table_name='request_stage_lead_times')
    op.drop_table('request_stage_lead_times')
    op.drop_index('ix_request_current_status_stage_delayed', table_name='request_current_status')
    op.drop_index('ix_request_current_status_criticality_delay', table_name='request_current_status')
    op.drop_table('request_current_status')
    op.drop_index('ix_purchase_orders_vendor_status', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_request_id', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('ix_procurement_stage_events_type_status', table_name='procurement_stage_events')
    op.drop_index('ix_procurement_stage_events_stage_time', table_name='procurement_stage_events')
    op.drop_index('ix_procurement_stage_events_request_time', table_name='procurement_stage_events')
    op.drop_table('procurement_stage_events')
    op.drop_index('ix_critical_request_queue_score', table_name='critical_request_queue')
    op.drop_index('ix_critical_request_queue_rank', table_name='critical_request_queue')
    op.drop_table('critical_request_queue')
    op.drop_index('ix_purchase_requests_department_status', table_name='purchase_requests')
    op.drop_index('ix_purchase_requests_current_stage', table_name='purchase_requests')
    op.drop_index('ix_purchase_requests_criticality_needed_by', table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_index('ix_vendor_delay_summary_delay_rate', table_name='vendor_delay_summary')
    op.drop_table('vendor_delay_summary')
    op.drop_index('ix_requesters_department_id', table_name='requesters')
    op.drop_table('requesters')
    op.drop_index('ix_vendors_reliability_tier', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_raw_vendor_updates_pipeline_run_id'), table_name='raw_vendor_updates')
    op.drop_index('ix_raw_vendor_update_pipeline_source', table_name='raw_vendor_updates')
    op.drop_table('raw_vendor_updates')
    op.drop_index(op.f('ix_raw_stage_events_pipeline_run_id'), table_name='raw_stage_events')
    op.drop_index('ix_raw_stage_event_pipeline_source', table_name='raw_stage_events')
    op.drop_table('raw_stage_events')
    op.drop_index(op.f('ix_raw_receipts_pipeline_run_id'), table_name='raw_receipts')
    op.drop_index('ix_raw_receipt_pipeline_source', table_name='raw_receipts')
    op.drop_table('raw_receipts')
    op.drop_index(op.f('ix_raw_purchase_requests_pipeline_run_id'), table_name='raw_purchase_requests')
    op.drop_index('ix_raw_pr_pipeline_source', table_name='raw_purchase_requests')
    op.drop_table('raw_purchase_requests')
    op.drop_index(op.f('ix_raw_purchase_orders_pipeline_run_id'), table_name='raw_purchase_orders')
    op.drop_index('ix_raw_po_pipeline_source', table_name='raw_purchase_orders')
    op.drop_table('raw_purchase_orders')
    op.drop_index('ix_pipeline_runs_status', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_name_started', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_items_category_critical', table_name='items')
    op.drop_table('items')
    op.drop_table('departments')
    op.drop_index('ix_dq_results_target_table', table_name='data_quality_check_results')
    op.drop_index('ix_dq_results_severity', table_name='data_quality_check_results')
    op.drop_index('ix_dq_results_run_status', table_name='data_quality_check_results')
    op.drop_index(op.f('ix_data_quality_check_results_pipeline_run_id'), table_name='data_quality_check_results')
    op.drop_table('data_quality_check_results')
    op.drop_index('ix_bottleneck_summary_stage_delay', table_name='bottleneck_summary')
    op.drop_index('ix_bottleneck_summary_date_dimension', table_name='bottleneck_summary')
    op.drop_table('bottleneck_summary')
    # ### end Alembic commands ###
